sudo: false
language: node_js
node_js:
  - 'node'
  - '9'
install: cd 04-configure-jest-for-javascript-applications && npm install
script: cd 04-configure-jest-for-javascript-applications && npm test
after_script: npx codecov03
branches:
  only: master
